Update hugo.yaml

diff --git a/.github/workflows/hugo.yaml b/.github/workflows/hugo.yaml
--- a/.github/workflows/hugo.yaml
+++ b/.github/workflows/hugo.yaml
@@ -69,11 +69,18 @@ jobs:
       - name: List downloaded files
         run: ls -la ./public
       - name: Unzip artifact
-        run: unzip -q ./public/hugo-site.zip -d ./public
+        run: |
+          if [ -f "./public/hugo-site.zip" ]; then
+            unzip -q ./public/hugo-site.zip -d ./public
+          else
+            echo "Error: ./public/hugo-site.zip not found"
+            exit 1
+          fi
       - name: List unzipped content
         run: ls -la ./public
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v2
         with:
+          token: ${{ secrets.GITHUB_TOKEN }}
           build_path: ./public
